-- https://school.programmers.co.kr/learn/courses/30/lessons/133026, [성분으로 구분한 아이스크림 총 주문량]

SELECT
    II.INGREDIENT_TYPE,
    SUM(FH.TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF as FH
JOIN ICECREAM_INFO as II
ON FH.FLAVOR = II.FLAVOR
GROUP BY II.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;